// catch block
        
        console.log("Handled the error by logging it", err);